#
# Makefile
#
# Computer Science 50
# Problem Set 4
#

copy: copy.c bmp.h
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o copy copy.c -lcs50 -lm

whodunit: whodunit.c bmp.h
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o whodunit whodunit.c -lcs50 -lm

resize: resize.c bmp.h
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o resize resize.c -lcs50 -lm